# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_st.ui'
#
# Created: Mon Jan 20 09:16:14 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_win_st(object):
    def setupUi(self, win_st):
        win_st.setObjectName(_fromUtf8("win_st"))
        win_st.setEnabled(True)
        win_st.resize(921, 585)
        win_st.setMinimumSize(QtCore.QSize(921, 585))
        win_st.setMaximumSize(QtCore.QSize(921, 585))
        win_st.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(win_st)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.lblBotStatus = QtGui.QLabel(self.centralwidget)
        self.lblBotStatus.setEnabled(True)
        self.lblBotStatus.setGeometry(QtCore.QRect(365, 565, 56, 16))
        self.lblBotStatus.setAutoFillBackground(False)
        self.lblBotStatus.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 85, 127);"))
        self.lblBotStatus.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblBotStatus.setFrameShadow(QtGui.QFrame.Plain)
        self.lblBotStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBotStatus.setMargin(0)
        self.lblBotStatus.setObjectName(_fromUtf8("lblBotStatus"))
        self.lblBotMsg = QtGui.QLabel(self.centralwidget)
        self.lblBotMsg.setEnabled(False)
        self.lblBotMsg.setGeometry(QtCore.QRect(425, 565, 491, 16))
        self.lblBotMsg.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.lblBotMsg.setFrameShape(QtGui.QFrame.Box)
        self.lblBotMsg.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblBotMsg.setMargin(0)
        self.lblBotMsg.setObjectName(_fromUtf8("lblBotMsg"))
        self.lblBotDim = QtGui.QLabel(self.centralwidget)
        self.lblBotDim.setEnabled(False)
        self.lblBotDim.setGeometry(QtCore.QRect(5, 565, 161, 16))
        self.lblBotDim.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.lblBotDim.setFrameShape(QtGui.QFrame.Box)
        self.lblBotDim.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblBotDim.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBotDim.setMargin(0)
        self.lblBotDim.setObjectName(_fromUtf8("lblBotDim"))
        self.lblBotPockel = QtGui.QLabel(self.centralwidget)
        self.lblBotPockel.setEnabled(False)
        self.lblBotPockel.setGeometry(QtCore.QRect(170, 565, 56, 16))
        self.lblBotPockel.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.lblBotPockel.setFrameShape(QtGui.QFrame.Box)
        self.lblBotPockel.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblBotPockel.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBotPockel.setMargin(0)
        self.lblBotPockel.setObjectName(_fromUtf8("lblBotPockel"))
        self.lblBotPmt = QtGui.QLabel(self.centralwidget)
        self.lblBotPmt.setEnabled(False)
        self.lblBotPmt.setGeometry(QtCore.QRect(230, 565, 131, 16))
        self.lblBotPmt.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.lblBotPmt.setFrameShape(QtGui.QFrame.Box)
        self.lblBotPmt.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblBotPmt.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBotPmt.setMargin(0)
        self.lblBotPmt.setObjectName(_fromUtf8("lblBotPmt"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(230, 30, 686, 531))
        self.stackedWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QtGui.QFrame.Raised)
        self.stackedWidget.setLineWidth(1)
        self.stackedWidget.setMidLineWidth(1)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.pageLSeditor = QtGui.QWidget()
        self.pageLSeditor.setObjectName(_fromUtf8("pageLSeditor"))
        self.gbStructure = QtGui.QGroupBox(self.pageLSeditor)
        self.gbStructure.setGeometry(QtCore.QRect(550, 0, 136, 221))
        self.gbStructure.setFlat(False)
        self.gbStructure.setCheckable(False)
        self.gbStructure.setObjectName(_fromUtf8("gbStructure"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.gbStructure)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setContentsMargins(4, 0, 4, 4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.listStruct = QtGui.QListWidget(self.gbStructure)
        self.listStruct.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.listStruct.setFrameShape(QtGui.QFrame.Box)
        self.listStruct.setFrameShadow(QtGui.QFrame.Sunken)
        self.listStruct.setLineWidth(1)
        self.listStruct.setMidLineWidth(0)
        self.listStruct.setAlternatingRowColors(False)
        self.listStruct.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.listStruct.setViewMode(QtGui.QListView.ListMode)
        self.listStruct.setModelColumn(0)
        self.listStruct.setObjectName(_fromUtf8("listStruct"))
        item = QtGui.QListWidgetItem()
        self.listStruct.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listStruct.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listStruct.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listStruct.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listStruct.addItem(item)
        self.verticalLayout_4.addWidget(self.listStruct)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setSpacing(2)
        self.gridLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.btnStIns = QtGui.QPushButton(self.gbStructure)
        self.btnStIns.setAutoFillBackground(False)
        self.btnStIns.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.btnStIns.setFlat(False)
        self.btnStIns.setObjectName(_fromUtf8("btnStIns"))
        self.gridLayout_4.addWidget(self.btnStIns, 0, 0, 1, 1)
        self.btnStDel = QtGui.QPushButton(self.gbStructure)
        self.btnStDel.setAutoFillBackground(False)
        self.btnStDel.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.btnStDel.setFlat(False)
        self.btnStDel.setObjectName(_fromUtf8("btnStDel"))
        self.gridLayout_4.addWidget(self.btnStDel, 0, 1, 1, 1)
        self.btnStAuto = QtGui.QPushButton(self.gbStructure)
        self.btnStAuto.setAutoFillBackground(False)
        self.btnStAuto.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.btnStAuto.setFlat(False)
        self.btnStAuto.setObjectName(_fromUtf8("btnStAuto"))
        self.gridLayout_4.addWidget(self.btnStAuto, 1, 0, 1, 1)
        self.btnStrRename = QtGui.QPushButton(self.gbStructure)
        self.btnStrRename.setAutoFillBackground(False)
        self.btnStrRename.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.btnStrRename.setFlat(False)
        self.btnStrRename.setObjectName(_fromUtf8("btnStrRename"))
        self.gridLayout_4.addWidget(self.btnStrRename, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.lineStructure = QtGui.QLineEdit(self.gbStructure)
        self.lineStructure.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.lineStructure.setFrame(True)
        self.lineStructure.setObjectName(_fromUtf8("lineStructure"))
        self.verticalLayout_4.addWidget(self.lineStructure)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_3.setHorizontalSpacing(2)
        self.gridLayout_3.setVerticalSpacing(5)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lblStrB = QtGui.QLabel(self.gbStructure)
        self.lblStrB.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.lblStrB.setObjectName(_fromUtf8("lblStrB"))
        self.gridLayout_3.addWidget(self.lblStrB, 0, 1, 1, 1)
        self.lblStrA = QtGui.QLabel(self.gbStructure)
        self.lblStrA.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.lblStrA.setObjectName(_fromUtf8("lblStrA"))
        self.gridLayout_3.addWidget(self.lblStrA, 0, 0, 1, 1)
        self.lblStrW = QtGui.QLabel(self.gbStructure)
        self.lblStrW.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.lblStrW.setObjectName(_fromUtf8("lblStrW"))
        self.gridLayout_3.addWidget(self.lblStrW, 0, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.gbLinescan = QtGui.QGroupBox(self.pageLSeditor)
        self.gbLinescan.setGeometry(QtCore.QRect(0, 0, 546, 221))
        self.gbLinescan.setFlat(False)
        self.gbLinescan.setObjectName(_fromUtf8("gbLinescan"))
        self.lblRef = QtGui.QLabel(self.gbLinescan)
        self.lblRef.setGeometry(QtCore.QRect(5, 15, 200, 200))
        self.lblRef.setStyleSheet(_fromUtf8("background-color: rgb(160, 197, 255);"))
        self.lblRef.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRef.setObjectName(_fromUtf8("lblRef"))
        self.vs1 = QtGui.QSlider(self.gbLinescan)
        self.vs1.setGeometry(QtCore.QRect(510, 15, 16, 201))
        self.vs1.setPageStep(20)
        self.vs1.setProperty("value", 20)
        self.vs1.setOrientation(QtCore.Qt.Vertical)
        self.vs1.setObjectName(_fromUtf8("vs1"))
        self.vs2 = QtGui.QSlider(self.gbLinescan)
        self.vs2.setGeometry(QtCore.QRect(525, 15, 16, 201))
        self.vs2.setPageStep(20)
        self.vs2.setProperty("value", 25)
        self.vs2.setOrientation(QtCore.Qt.Vertical)
        self.vs2.setObjectName(_fromUtf8("vs2"))
        self.lblPK = QtGui.QLabel(self.gbLinescan)
        self.lblPK.setGeometry(QtCore.QRect(205, 15, 100, 200))
        self.lblPK.setStyleSheet(_fromUtf8("background-color: rgb(143, 133, 133);"))
        self.lblPK.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPK.setObjectName(_fromUtf8("lblPK"))
        self.lblLS = QtGui.QLabel(self.gbLinescan)
        self.lblLS.setGeometry(QtCore.QRect(305, 15, 200, 200))
        self.lblLS.setStyleSheet(_fromUtf8("background-color: rgb(110, 255, 151);"))
        self.lblLS.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLS.setObjectName(_fromUtf8("lblLS"))
        self.lblOL = QtGui.QLabel(self.gbLinescan)
        self.lblOL.setGeometry(QtCore.QRect(305, 15, 200, 200))
        self.lblOL.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblOL.setMidLineWidth(1)
        self.lblOL.setAlignment(QtCore.Qt.AlignCenter)
        self.lblOL.setObjectName(_fromUtf8("lblOL"))
        self.gbCalib = QtGui.QGroupBox(self.pageLSeditor)
        self.gbCalib.setGeometry(QtCore.QRect(95, 375, 136, 46))
        self.gbCalib.setCheckable(True)
        self.gbCalib.setChecked(True)
        self.gbCalib.setObjectName(_fromUtf8("gbCalib"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gbCalib)
        self.gridLayout_5.setContentsMargins(2, 0, 2, 2)
        self.gridLayout_5.setHorizontalSpacing(2)
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.sbGmax = QtGui.QSpinBox(self.gbCalib)
        self.sbGmax.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.sbGmax.setFrame(False)
        self.sbGmax.setSuffix(_fromUtf8(""))
        self.sbGmax.setMaximum(5000)
        self.sbGmax.setProperty("value", 1234)
        self.sbGmax.setObjectName(_fromUtf8("sbGmax"))
        self.gridLayout_5.addWidget(self.sbGmax, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gbCalib)
        self.label_3.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.sbRmax = QtGui.QSpinBox(self.gbCalib)
        self.sbRmax.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.sbRmax.setFrame(False)
        self.sbRmax.setSuffix(_fromUtf8(""))
        self.sbRmax.setMaximum(5000)
        self.sbRmax.setProperty("value", 987)
        self.sbRmax.setObjectName(_fromUtf8("sbRmax"))
        self.gridLayout_5.addWidget(self.sbRmax, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gbCalib)
        self.label_4.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.gbCalib)
        self.label_10.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 0, 2, 1, 1)
        self.lblM = QtGui.QLabel(self.gbCalib)
        self.lblM.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.lblM.setAlignment(QtCore.Qt.AlignCenter)
        self.lblM.setObjectName(_fromUtf8("lblM"))
        self.gridLayout_5.addWidget(self.lblM, 1, 2, 1, 1)
        self.gbTime = QtGui.QGroupBox(self.pageLSeditor)
        self.gbTime.setGeometry(QtCore.QRect(95, 250, 136, 121))
        self.gbTime.setObjectName(_fromUtf8("gbTime"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gbTime)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(2, 0, 2, 2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setHorizontalSpacing(1)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineAV = QtGui.QLineEdit(self.gbTime)
        self.lineAV.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.lineAV.setFrame(False)
        self.lineAV.setReadOnly(True)
        self.lineAV.setObjectName(_fromUtf8("lineAV"))
        self.gridLayout.addWidget(self.lineAV, 4, 1, 1, 1)
        self.linePK = QtGui.QLineEdit(self.gbTime)
        self.linePK.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.linePK.setFrame(False)
        self.linePK.setReadOnly(True)
        self.linePK.setObjectName(_fromUtf8("linePK"))
        self.gridLayout.addWidget(self.linePK, 5, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.gbTime)
        self.label_11.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.gbTime)
        self.label_19.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 2, 0, 1, 1)
        self.lineBL = QtGui.QLineEdit(self.gbTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineBL.sizePolicy().hasHeightForWidth())
        self.lineBL.setSizePolicy(sizePolicy)
        self.lineBL.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.lineBL.setFrame(True)
        self.lineBL.setObjectName(_fromUtf8("lineBL"))
        self.gridLayout.addWidget(self.lineBL, 0, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.gbTime)
        self.label_15.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.gbTime)
        self.label_14.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.lineMS = QtGui.QLineEdit(self.gbTime)
        self.lineMS.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.lineMS.setFrame(True)
        self.lineMS.setObjectName(_fromUtf8("lineMS"))
        self.gridLayout.addWidget(self.lineMS, 2, 1, 1, 1)
        self.lineEV = QtGui.QLineEdit(self.gbTime)
        self.lineEV.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.lineEV.setFrame(True)
        self.lineEV.setObjectName(_fromUtf8("lineEV"))
        self.gridLayout.addWidget(self.lineEV, 1, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.gbTime)
        self.label_12.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 5, 0, 1, 1)
        self.btnTimeUpdate = QtGui.QPushButton(self.gbTime)
        self.btnTimeUpdate.setObjectName(_fromUtf8("btnTimeUpdate"))
        self.gridLayout.addWidget(self.btnTimeUpdate, 3, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.gbPreview = QtGui.QGroupBox(self.pageLSeditor)
        self.gbPreview.setGeometry(QtCore.QRect(95, 420, 136, 111))
        self.gbPreview.setCheckable(False)
        self.gbPreview.setChecked(False)
        self.gbPreview.setObjectName(_fromUtf8("gbPreview"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.gbPreview)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(2, 0, 2, 2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.cbPrv = QtGui.QComboBox(self.gbPreview)
        self.cbPrv.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.cbPrv.setObjectName(_fromUtf8("cbPrv"))
        self.cbPrv.addItem(_fromUtf8(""))
        self.cbPrv.addItem(_fromUtf8(""))
        self.cbPrv.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.cbPrv)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.cbPrvMax = QtGui.QCheckBox(self.gbPreview)
        self.cbPrvMax.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbPrvMax.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.cbPrvMax.setObjectName(_fromUtf8("cbPrvMax"))
        self.gridLayout_6.addWidget(self.cbPrvMax, 0, 0, 1, 1)
        self.cbPrvMin = QtGui.QCheckBox(self.gbPreview)
        self.cbPrvMin.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.cbPrvMin.setObjectName(_fromUtf8("cbPrvMin"))
        self.gridLayout_6.addWidget(self.cbPrvMin, 1, 0, 1, 1)
        self.linePrvMax = QtGui.QLineEdit(self.gbPreview)
        self.linePrvMax.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.linePrvMax.setFrame(True)
        self.linePrvMax.setObjectName(_fromUtf8("linePrvMax"))
        self.gridLayout_6.addWidget(self.linePrvMax, 0, 1, 1, 1)
        self.linePrvMin = QtGui.QLineEdit(self.gbPreview)
        self.linePrvMin.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.linePrvMin.setFrame(True)
        self.linePrvMin.setObjectName(_fromUtf8("linePrvMin"))
        self.gridLayout_6.addWidget(self.linePrvMin, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_6)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.btnPrvSweeps = QtGui.QPushButton(self.gbPreview)
        self.btnPrvSweeps.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.btnPrvSweeps.setCheckable(True)
        self.btnPrvSweeps.setChecked(False)
        self.btnPrvSweeps.setObjectName(_fromUtf8("btnPrvSweeps"))
        self.gridLayout_9.addWidget(self.btnPrvSweeps, 0, 0, 1, 1)
        self.btnPrvPNG = QtGui.QPushButton(self.gbPreview)
        self.btnPrvPNG.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.btnPrvPNG.setObjectName(_fromUtf8("btnPrvPNG"))
        self.gridLayout_9.addWidget(self.btnPrvPNG, 0, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_9)
        self.gbCycles = QtGui.QGroupBox(self.pageLSeditor)
        self.gbCycles.setGeometry(QtCore.QRect(0, 220, 91, 311))
        self.gbCycles.setObjectName(_fromUtf8("gbCycles"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gbCycles)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setMargin(5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.listCycles = QtGui.QListWidget(self.gbCycles)
        self.listCycles.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.listCycles.setFrameShape(QtGui.QFrame.Box)
        self.listCycles.setFrameShadow(QtGui.QFrame.Sunken)
        self.listCycles.setLineWidth(1)
        self.listCycles.setMidLineWidth(0)
        self.listCycles.setAlternatingRowColors(False)
        self.listCycles.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listCycles.setMovement(QtGui.QListView.Static)
        self.listCycles.setFlow(QtGui.QListView.TopToBottom)
        self.listCycles.setLayoutMode(QtGui.QListView.SinglePass)
        self.listCycles.setViewMode(QtGui.QListView.IconMode)
        self.listCycles.setModelColumn(0)
        self.listCycles.setUniformItemSizes(False)
        self.listCycles.setObjectName(_fromUtf8("listCycles"))
        item = QtGui.QListWidgetItem()
        self.listCycles.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listCycles.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listCycles.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listCycles.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listCycles.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listCycles.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listCycles.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listCycles.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listCycles.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listCycles.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listCycles.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listCycles.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listCycles.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listCycles.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listCycles.addItem(item)
        self.verticalLayout_2.addWidget(self.listCycles)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btnCycle1 = QtGui.QPushButton(self.gbCycles)
        self.btnCycle1.setAutoFillBackground(False)
        self.btnCycle1.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.btnCycle1.setCheckable(True)
        self.btnCycle1.setFlat(False)
        self.btnCycle1.setObjectName(_fromUtf8("btnCycle1"))
        self.horizontalLayout_5.addWidget(self.btnCycle1)
        self.btnCycleAll = QtGui.QPushButton(self.gbCycles)
        self.btnCycleAll.setAutoFillBackground(False)
        self.btnCycleAll.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.btnCycleAll.setFlat(False)
        self.btnCycleAll.setObjectName(_fromUtf8("btnCycleAll"))
        self.horizontalLayout_5.addWidget(self.btnCycleAll)
        self.btnCycleNone = QtGui.QPushButton(self.gbCycles)
        self.btnCycleNone.setAutoFillBackground(False)
        self.btnCycleNone.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.btnCycleNone.setFlat(False)
        self.btnCycleNone.setObjectName(_fromUtf8("btnCycleNone"))
        self.horizontalLayout_5.addWidget(self.btnCycleNone)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.line = QtGui.QFrame(self.gbCycles)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.label_5 = QtGui.QLabel(self.gbCycles)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.sbGaussSpace = QtGui.QSpinBox(self.gbCycles)
        self.sbGaussSpace.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.sbGaussSpace.setFrame(False)
        self.sbGaussSpace.setSuffix(_fromUtf8(""))
        self.sbGaussSpace.setMaximum(999)
        self.sbGaussSpace.setProperty("value", 2)
        self.sbGaussSpace.setObjectName(_fromUtf8("sbGaussSpace"))
        self.gridLayout_2.addWidget(self.sbGaussSpace, 2, 0, 1, 1)
        self.sbGaussTime = QtGui.QSpinBox(self.gbCycles)
        self.sbGaussTime.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.sbGaussTime.setFrame(False)
        self.sbGaussTime.setSuffix(_fromUtf8(""))
        self.sbGaussTime.setProperty("value", 4)
        self.sbGaussTime.setObjectName(_fromUtf8("sbGaussTime"))
        self.gridLayout_2.addWidget(self.sbGaussTime, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.gbCycles)
        self.label_6.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gbCycles)
        self.label_7.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 3, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.lblGraph = QtGui.QLabel(self.pageLSeditor)
        self.lblGraph.setGeometry(QtCore.QRect(235, 230, 450, 300))
        self.lblGraph.setStyleSheet(_fromUtf8("background-color: rgb(246, 201, 255);"))
        self.lblGraph.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGraph.setObjectName(_fromUtf8("lblGraph"))
        self.gbPreview_2 = QtGui.QGroupBox(self.pageLSeditor)
        self.gbPreview_2.setGeometry(QtCore.QRect(95, 220, 133, 31))
        self.gbPreview_2.setCheckable(False)
        self.gbPreview_2.setChecked(False)
        self.gbPreview_2.setObjectName(_fromUtf8("gbPreview_2"))
        self.gridLayout_12 = QtGui.QGridLayout(self.gbPreview_2)
        self.gridLayout_12.setContentsMargins(2, 0, 2, 2)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.cbLS = QtGui.QComboBox(self.gbPreview_2)
        self.cbLS.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.cbLS.setObjectName(_fromUtf8("cbLS"))
        self.cbLS.addItem(_fromUtf8(""))
        self.cbLS.addItem(_fromUtf8(""))
        self.cbLS.addItem(_fromUtf8(""))
        self.gridLayout_12.addWidget(self.cbLS, 0, 0, 1, 1)
        self.cbStretch = QtGui.QCheckBox(self.gbPreview_2)
        self.cbStretch.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbStretch.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.cbStretch.setObjectName(_fromUtf8("cbStretch"))
        self.gridLayout_12.addWidget(self.cbStretch, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.pageLSeditor)
        self.pageLSreport = QtGui.QWidget()
        self.pageLSreport.setObjectName(_fromUtf8("pageLSreport"))
        self.gbReport = QtGui.QGroupBox(self.pageLSreport)
        self.gbReport.setGeometry(QtCore.QRect(0, 0, 686, 41))
        self.gbReport.setFlat(False)
        self.gbReport.setObjectName(_fromUtf8("gbReport"))
        self.btnHTMLgen = QtGui.QPushButton(self.gbReport)
        self.btnHTMLgen.setGeometry(QtCore.QRect(5, 15, 81, 21))
        self.btnHTMLgen.setObjectName(_fromUtf8("btnHTMLgen"))
        self.btnHTMLrefresh = QtGui.QPushButton(self.gbReport)
        self.btnHTMLrefresh.setGeometry(QtCore.QRect(90, 15, 81, 21))
        self.btnHTMLrefresh.setObjectName(_fromUtf8("btnHTMLrefresh"))
        self.btnHTMLlaunch = QtGui.QPushButton(self.gbReport)
        self.btnHTMLlaunch.setGeometry(QtCore.QRect(175, 15, 81, 21))
        self.btnHTMLlaunch.setObjectName(_fromUtf8("btnHTMLlaunch"))
        self.frame_2 = QtGui.QFrame(self.pageLSreport)
        self.frame_2.setGeometry(QtCore.QRect(0, 45, 686, 486))
        self.frame_2.setFrameShape(QtGui.QFrame.Panel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.webView_report = QtWebKit.QWebView(self.frame_2)
        self.webView_report.setAutoFillBackground(False)
        self.webView_report.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.webView_report.setZoomFactor(0.75)
        self.webView_report.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.webView_report.setObjectName(_fromUtf8("webView_report"))
        self.verticalLayout_8.addWidget(self.webView_report)
        self.stackedWidget.addWidget(self.pageLSreport)
        self.pageLSexperiment = QtGui.QWidget()
        self.pageLSexperiment.setObjectName(_fromUtf8("pageLSexperiment"))
        self.groupBox = QtGui.QGroupBox(self.pageLSexperiment)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 256, 531))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.frame_4 = QtGui.QFrame(self.groupBox)
        self.frame_4.setGeometry(QtCore.QRect(5, 15, 246, 511))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout_15 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_15.setMargin(0)
        self.gridLayout_15.setSpacing(0)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.btnExpLaunch = QtGui.QPushButton(self.frame_4)
        self.btnExpLaunch.setObjectName(_fromUtf8("btnExpLaunch"))
        self.gridLayout_15.addWidget(self.btnExpLaunch, 5, 0, 1, 1)
        self.listExperiments = QtGui.QListWidget(self.frame_4)
        self.listExperiments.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.listExperiments.setFrameShape(QtGui.QFrame.Box)
        self.listExperiments.setFrameShadow(QtGui.QFrame.Sunken)
        self.listExperiments.setLineWidth(1)
        self.listExperiments.setMidLineWidth(0)
        self.listExperiments.setAlternatingRowColors(True)
        self.listExperiments.setViewMode(QtGui.QListView.ListMode)
        self.listExperiments.setModelColumn(0)
        self.listExperiments.setObjectName(_fromUtf8("listExperiments"))
        item = QtGui.QListWidgetItem()
        self.listExperiments.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listExperiments.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listExperiments.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listExperiments.addItem(item)
        self.gridLayout_15.addWidget(self.listExperiments, 3, 0, 1, 1)
        self.frame_5 = QtGui.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_16 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 2)
        self.gridLayout_16.setHorizontalSpacing(2)
        self.gridLayout_16.setVerticalSpacing(0)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.btnExpLoad = QtGui.QPushButton(self.frame_5)
        self.btnExpLoad.setObjectName(_fromUtf8("btnExpLoad"))
        self.gridLayout_16.addWidget(self.btnExpLoad, 0, 0, 1, 1)
        self.btnExpSave = QtGui.QPushButton(self.frame_5)
        self.btnExpSave.setObjectName(_fromUtf8("btnExpSave"))
        self.gridLayout_16.addWidget(self.btnExpSave, 0, 1, 1, 1)
        self.btnExpPush = QtGui.QPushButton(self.frame_5)
        self.btnExpPush.setObjectName(_fromUtf8("btnExpPush"))
        self.gridLayout_16.addWidget(self.btnExpPush, 1, 1, 1, 1)
        self.btnExpPull = QtGui.QPushButton(self.frame_5)
        self.btnExpPull.setObjectName(_fromUtf8("btnExpPull"))
        self.gridLayout_16.addWidget(self.btnExpPull, 1, 0, 1, 1)
        self.gridLayout_15.addWidget(self.frame_5, 1, 0, 1, 1)
        self.frame_6 = QtGui.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.gridLayout_17 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 2)
        self.gridLayout_17.setHorizontalSpacing(2)
        self.gridLayout_17.setVerticalSpacing(0)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.btnExpClear = QtGui.QPushButton(self.frame_6)
        self.btnExpClear.setObjectName(_fromUtf8("btnExpClear"))
        self.gridLayout_17.addWidget(self.btnExpClear, 0, 1, 1, 1)
        self.btnExpDel = QtGui.QPushButton(self.frame_6)
        self.btnExpDel.setObjectName(_fromUtf8("btnExpDel"))
        self.gridLayout_17.addWidget(self.btnExpDel, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.frame_6, 4, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.pageLSexperiment)
        self.groupBox_3.setGeometry(QtCore.QRect(260, 0, 421, 531))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_18 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_18.setSpacing(0)
        self.gridLayout_18.setContentsMargins(5, 0, 5, 5)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.teExperimentCode = QtGui.QPlainTextEdit(self.groupBox_3)
        self.teExperimentCode.setStyleSheet(_fromUtf8("font: 8pt \"Consolas\";"))
        self.teExperimentCode.setFrameShape(QtGui.QFrame.Box)
        self.teExperimentCode.setFrameShadow(QtGui.QFrame.Sunken)
        self.teExperimentCode.setLineWidth(1)
        self.teExperimentCode.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.teExperimentCode.setReadOnly(False)
        self.teExperimentCode.setBackgroundVisible(False)
        self.teExperimentCode.setObjectName(_fromUtf8("teExperimentCode"))
        self.gridLayout_18.addWidget(self.teExperimentCode, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageLSexperiment)
        self.pageData = QtGui.QWidget()
        self.pageData.setObjectName(_fromUtf8("pageData"))
        self.groupBox_2 = QtGui.QGroupBox(self.pageData)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 686, 531))
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.teConfig = QtGui.QPlainTextEdit(self.groupBox_2)
        self.teConfig.setGeometry(QtCore.QRect(5, 15, 676, 511))
        self.teConfig.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"font: 75 12pt \"Consolas\";\n"
"color: rgb(85, 255, 127);"))
        self.teConfig.setFrameShape(QtGui.QFrame.NoFrame)
        self.teConfig.setFrameShadow(QtGui.QFrame.Plain)
        self.teConfig.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.teConfig.setReadOnly(True)
        self.teConfig.setBackgroundVisible(False)
        self.teConfig.setObjectName(_fromUtf8("teConfig"))
        self.stackedWidget.addWidget(self.pageData)
        self.pageChangelog = QtGui.QWidget()
        self.pageChangelog.setObjectName(_fromUtf8("pageChangelog"))
        self.frame = QtGui.QFrame(self.pageChangelog)
        self.frame.setGeometry(QtCore.QRect(0, 140, 686, 391))
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setLineWidth(1)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.webView = QtWebKit.QWebView(self.frame)
        self.webView.setAutoFillBackground(False)
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("http://swharden.com/version/SAG/changelog.html")))
        self.webView.setZoomFactor(0.75)
        self.webView.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.webView.setObjectName(_fromUtf8("webView"))
        self.verticalLayout_7.addWidget(self.webView)
        self.gbRegistration = QtGui.QGroupBox(self.pageChangelog)
        self.gbRegistration.setGeometry(QtCore.QRect(170, 5, 296, 131))
        self.gbRegistration.setObjectName(_fromUtf8("gbRegistration"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gbRegistration)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_9 = QtGui.QLabel(self.gbRegistration)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_8.addWidget(self.label_9, 1, 0, 1, 1)
        self.lblRegPCID = QtGui.QLabel(self.gbRegistration)
        self.lblRegPCID.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblRegPCID.setObjectName(_fromUtf8("lblRegPCID"))
        self.gridLayout_8.addWidget(self.lblRegPCID, 1, 1, 1, 1)
        self.lblRegName = QtGui.QLabel(self.gbRegistration)
        self.lblRegName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblRegName.setObjectName(_fromUtf8("lblRegName"))
        self.gridLayout_8.addWidget(self.lblRegName, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gbRegistration)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_8.addWidget(self.label_2, 0, 0, 1, 1)
        self.lblRegKey = QtGui.QLabel(self.gbRegistration)
        self.lblRegKey.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblRegKey.setObjectName(_fromUtf8("lblRegKey"))
        self.gridLayout_8.addWidget(self.lblRegKey, 2, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.gbRegistration)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_8.addWidget(self.label_13, 2, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.pageChangelog)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 5, 166, 131))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_11.addWidget(self.label_8, 0, 0, 1, 1)
        self.lblVersion2 = QtGui.QLabel(self.groupBox_5)
        self.lblVersion2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblVersion2.setObjectName(_fromUtf8("lblVersion2"))
        self.gridLayout_11.addWidget(self.lblVersion2, 0, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.groupBox_5)
        self.pushButton.setEnabled(False)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_11.addWidget(self.pushButton, 2, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.groupBox_5)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_11.addWidget(self.label_28, 2, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_5)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_11.addWidget(self.label_16, 1, 0, 1, 1)
        self.lblDistDate = QtGui.QLabel(self.groupBox_5)
        self.lblDistDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblDistDate.setObjectName(_fromUtf8("lblDistDate"))
        self.gridLayout_11.addWidget(self.lblDistDate, 1, 1, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.pageChangelog)
        self.groupBox_6.setGeometry(QtCore.QRect(470, 5, 216, 131))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_13.setMargin(0)
        self.gridLayout_13.setSpacing(0)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.teLicense = QtGui.QTextEdit(self.groupBox_6)
        self.teLicense.setEnabled(True)
        self.teLicense.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(175, 175, 175);"))
        self.teLicense.setFrameShape(QtGui.QFrame.NoFrame)
        self.teLicense.setFrameShadow(QtGui.QFrame.Plain)
        self.teLicense.setLineWidth(0)
        self.teLicense.setReadOnly(True)
        self.teLicense.setAcceptRichText(False)
        self.teLicense.setObjectName(_fromUtf8("teLicense"))
        self.gridLayout_13.addWidget(self.teLicense, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageChangelog)
        self.pageZseries = QtGui.QWidget()
        self.pageZseries.setObjectName(_fromUtf8("pageZseries"))
        self.groupBox_4 = QtGui.QGroupBox(self.pageZseries)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 0, 686, 531))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.btnZproj = QtGui.QPushButton(self.groupBox_4)
        self.btnZproj.setGeometry(QtCore.QRect(5, 20, 166, 41))
        self.btnZproj.setObjectName(_fromUtf8("btnZproj"))
        self.lblZa = QtGui.QLabel(self.groupBox_4)
        self.lblZa.setGeometry(QtCore.QRect(175, 20, 250, 250))
        self.lblZa.setStyleSheet(_fromUtf8("background-color: rgb(184, 214, 222);"))
        self.lblZa.setText(_fromUtf8(""))
        self.lblZa.setScaledContents(True)
        self.lblZa.setObjectName(_fromUtf8("lblZa"))
        self.lblZb = QtGui.QLabel(self.groupBox_4)
        self.lblZb.setGeometry(QtCore.QRect(175, 275, 250, 250))
        self.lblZb.setStyleSheet(_fromUtf8("background-color: rgb(184, 214, 222);"))
        self.lblZb.setText(_fromUtf8(""))
        self.lblZb.setScaledContents(True)
        self.lblZb.setObjectName(_fromUtf8("lblZb"))
        self.lblZc = QtGui.QLabel(self.groupBox_4)
        self.lblZc.setGeometry(QtCore.QRect(430, 20, 250, 250))
        self.lblZc.setStyleSheet(_fromUtf8("background-color: rgb(184, 214, 222);"))
        self.lblZc.setText(_fromUtf8(""))
        self.lblZc.setScaledContents(True)
        self.lblZc.setObjectName(_fromUtf8("lblZc"))
        self.lblZd = QtGui.QLabel(self.groupBox_4)
        self.lblZd.setGeometry(QtCore.QRect(430, 275, 250, 250))
        self.lblZd.setStyleSheet(_fromUtf8("background-color: rgb(184, 214, 222);"))
        self.lblZd.setText(_fromUtf8(""))
        self.lblZd.setScaledContents(True)
        self.lblZd.setObjectName(_fromUtf8("lblZd"))
        self.stackedWidget.addWidget(self.pageZseries)
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.groupBox_7 = QtGui.QGroupBox(self.page)
        self.groupBox_7.setGeometry(QtCore.QRect(0, 0, 686, 531))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.slideT = QtGui.QSlider(self.groupBox_7)
        self.slideT.setGeometry(QtCore.QRect(15, 455, 626, 31))
        self.slideT.setPageStep(1)
        self.slideT.setOrientation(QtCore.Qt.Horizontal)
        self.slideT.setObjectName(_fromUtf8("slideT"))
        self.lblT = QtGui.QLabel(self.groupBox_7)
        self.lblT.setGeometry(QtCore.QRect(240, 45, 400, 400))
        self.lblT.setText(_fromUtf8(""))
        self.lblT.setScaledContents(True)
        self.lblT.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lblT.setObjectName(_fromUtf8("lblT"))
        self.btnTgen = QtGui.QPushButton(self.groupBox_7)
        self.btnTgen.setGeometry(QtCore.QRect(20, 50, 186, 46))
        self.btnTgen.setCheckable(True)
        self.btnTgen.setObjectName(_fromUtf8("btnTgen"))
        self.lblT2 = QtGui.QLabel(self.groupBox_7)
        self.lblT2.setGeometry(QtCore.QRect(15, 105, 216, 341))
        self.lblT2.setText(_fromUtf8(""))
        self.lblT2.setScaledContents(False)
        self.lblT2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lblT2.setObjectName(_fromUtf8("lblT2"))
        self.stackedWidget.addWidget(self.page)
        self.lblProgram = QtGui.QLabel(self.centralwidget)
        self.lblProgram.setGeometry(QtCore.QRect(240, 0, 136, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lblProgram.setFont(font)
        self.lblProgram.setObjectName(_fromUtf8("lblProgram"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(440, 0, 476, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnPageLS = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnPageLS.setEnabled(False)
        self.btnPageLS.setObjectName(_fromUtf8("btnPageLS"))
        self.horizontalLayout.addWidget(self.btnPageLS)
        self.btnPageLSreport = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnPageLSreport.setEnabled(False)
        self.btnPageLSreport.setObjectName(_fromUtf8("btnPageLSreport"))
        self.horizontalLayout.addWidget(self.btnPageLSreport)
        self.btnPageExperiment = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnPageExperiment.setEnabled(False)
        self.btnPageExperiment.setObjectName(_fromUtf8("btnPageExperiment"))
        self.horizontalLayout.addWidget(self.btnPageExperiment)
        self.btnPageXML = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnPageXML.setEnabled(False)
        self.btnPageXML.setObjectName(_fromUtf8("btnPageXML"))
        self.horizontalLayout.addWidget(self.btnPageXML)
        self.btnPageConfig = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnPageConfig.setEnabled(False)
        self.btnPageConfig.setObjectName(_fromUtf8("btnPageConfig"))
        self.horizontalLayout.addWidget(self.btnPageConfig)
        self.lblVersion = QtGui.QLabel(self.centralwidget)
        self.lblVersion.setGeometry(QtCore.QRect(375, 11, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblVersion.setFont(font)
        self.lblVersion.setStyleSheet(_fromUtf8("color: rgb(175, 175, 175);"))
        self.lblVersion.setObjectName(_fromUtf8("lblVersion"))
        self.listBrowser = QtGui.QListWidget(self.centralwidget)
        self.listBrowser.setGeometry(QtCore.QRect(5, 5, 221, 321))
        self.listBrowser.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.listBrowser.setFrameShape(QtGui.QFrame.Box)
        self.listBrowser.setFrameShadow(QtGui.QFrame.Sunken)
        self.listBrowser.setLineWidth(1)
        self.listBrowser.setMidLineWidth(0)
        self.listBrowser.setAlternatingRowColors(True)
        self.listBrowser.setViewMode(QtGui.QListView.ListMode)
        self.listBrowser.setModelColumn(0)
        self.listBrowser.setObjectName(_fromUtf8("listBrowser"))
        item = QtGui.QListWidgetItem()
        self.listBrowser.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listBrowser.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listBrowser.addItem(item)
        self.groupBox_9 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_9.setGeometry(QtCore.QRect(5, 330, 221, 91))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_7.setSpacing(2)
        self.gridLayout_7.setContentsMargins(2, 0, 2, 0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.btnBrowserLaunch = QtGui.QPushButton(self.groupBox_9)
        self.btnBrowserLaunch.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.btnBrowserLaunch.setObjectName(_fromUtf8("btnBrowserLaunch"))
        self.gridLayout_7.addWidget(self.btnBrowserLaunch, 0, 3, 1, 1)
        self.btnBrowserPath = QtGui.QPushButton(self.groupBox_9)
        self.btnBrowserPath.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.btnBrowserPath.setObjectName(_fromUtf8("btnBrowserPath"))
        self.gridLayout_7.addWidget(self.btnBrowserPath, 0, 0, 1, 1)
        self.btnBrowserRefresh = QtGui.QPushButton(self.groupBox_9)
        self.btnBrowserRefresh.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.btnBrowserRefresh.setObjectName(_fromUtf8("btnBrowserRefresh"))
        self.gridLayout_7.addWidget(self.btnBrowserRefresh, 0, 2, 1, 1)
        self.cbBrL = QtGui.QCheckBox(self.groupBox_9)
        self.cbBrL.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.cbBrL.setObjectName(_fromUtf8("cbBrL"))
        self.gridLayout_7.addWidget(self.cbBrL, 1, 2, 1, 1)
        self.cbBrS = QtGui.QCheckBox(self.groupBox_9)
        self.cbBrS.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.cbBrS.setObjectName(_fromUtf8("cbBrS"))
        self.gridLayout_7.addWidget(self.cbBrS, 1, 0, 1, 1)
        self.cbBrZ = QtGui.QCheckBox(self.groupBox_9)
        self.cbBrZ.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.cbBrZ.setObjectName(_fromUtf8("cbBrZ"))
        self.gridLayout_7.addWidget(self.cbBrZ, 2, 0, 1, 1)
        self.cbBrT = QtGui.QCheckBox(self.groupBox_9)
        self.cbBrT.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.cbBrT.setObjectName(_fromUtf8("cbBrT"))
        self.gridLayout_7.addWidget(self.cbBrT, 1, 3, 1, 1)
        self.cbBrAll = QtGui.QCheckBox(self.groupBox_9)
        self.cbBrAll.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.cbBrAll.setObjectName(_fromUtf8("cbBrAll"))
        self.gridLayout_7.addWidget(self.cbBrAll, 2, 3, 1, 1)
        self.cbBrA = QtGui.QCheckBox(self.groupBox_9)
        self.cbBrA.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.cbBrA.setObjectName(_fromUtf8("cbBrA"))
        self.gridLayout_7.addWidget(self.cbBrA, 2, 2, 1, 1)
        self.sbAtLeast = QtGui.QSpinBox(self.groupBox_9)
        self.sbAtLeast.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.sbAtLeast.setFrame(False)
        self.sbAtLeast.setSuffix(_fromUtf8(""))
        self.sbAtLeast.setProperty("value", 4)
        self.sbAtLeast.setObjectName(_fromUtf8("sbAtLeast"))
        self.gridLayout_7.addWidget(self.sbAtLeast, 3, 3, 1, 1)
        self.cbAtLeast = QtGui.QCheckBox(self.groupBox_9)
        self.cbAtLeast.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.cbAtLeast.setObjectName(_fromUtf8("cbAtLeast"))
        self.gridLayout_7.addWidget(self.cbAtLeast, 3, 2, 1, 1)
        self.cbBrH = QtGui.QCheckBox(self.groupBox_9)
        self.cbBrH.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.cbBrH.setObjectName(_fromUtf8("cbBrH"))
        self.gridLayout_7.addWidget(self.cbBrH, 3, 0, 1, 1)
        self.btnBrowserStore = QtGui.QPushButton(self.groupBox_9)
        self.btnBrowserStore.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.btnBrowserStore.setObjectName(_fromUtf8("btnBrowserStore"))
        self.gridLayout_7.addWidget(self.btnBrowserStore, 0, 1, 1, 1)
        self.gbConfiguration = QtGui.QGroupBox(self.centralwidget)
        self.gbConfiguration.setGeometry(QtCore.QRect(5, 425, 221, 61))
        self.gbConfiguration.setObjectName(_fromUtf8("gbConfiguration"))
        self.verticalLayout = QtGui.QVBoxLayout(self.gbConfiguration)
        self.verticalLayout.setContentsMargins(2, 0, 2, 2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setSpacing(2)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.btnConfigClear = QtGui.QPushButton(self.gbConfiguration)
        self.btnConfigClear.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.btnConfigClear.setObjectName(_fromUtf8("btnConfigClear"))
        self.gridLayout_10.addWidget(self.btnConfigClear, 3, 1, 1, 1)
        self.btnConfigRevert = QtGui.QPushButton(self.gbConfiguration)
        self.btnConfigRevert.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.btnConfigRevert.setObjectName(_fromUtf8("btnConfigRevert"))
        self.gridLayout_10.addWidget(self.btnConfigRevert, 3, 0, 1, 1)
        self.btnConfigCopy = QtGui.QPushButton(self.gbConfiguration)
        self.btnConfigCopy.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.btnConfigCopy.setObjectName(_fromUtf8("btnConfigCopy"))
        self.gridLayout_10.addWidget(self.btnConfigCopy, 5, 0, 1, 1)
        self.btnConfigPaste = QtGui.QPushButton(self.gbConfiguration)
        self.btnConfigPaste.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.btnConfigPaste.setObjectName(_fromUtf8("btnConfigPaste"))
        self.gridLayout_10.addWidget(self.btnConfigPaste, 5, 1, 1, 1)
        self.btnConfigSave = QtGui.QPushButton(self.gbConfiguration)
        self.btnConfigSave.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.btnConfigSave.setObjectName(_fromUtf8("btnConfigSave"))
        self.gridLayout_10.addWidget(self.btnConfigSave, 3, 4, 1, 1)
        self.btnConfigFlag = QtGui.QPushButton(self.gbConfiguration)
        self.btnConfigFlag.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.btnConfigFlag.setObjectName(_fromUtf8("btnConfigFlag"))
        self.gridLayout_10.addWidget(self.btnConfigFlag, 5, 4, 1, 1)
        self.btnConfigHide = QtGui.QPushButton(self.gbConfiguration)
        self.btnConfigHide.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.btnConfigHide.setCheckable(True)
        self.btnConfigHide.setObjectName(_fromUtf8("btnConfigHide"))
        self.gridLayout_10.addWidget(self.btnConfigHide, 5, 2, 1, 1)
        self.btnExp = QtGui.QPushButton(self.gbConfiguration)
        self.btnExp.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.btnExp.setCheckable(True)
        self.btnExp.setObjectName(_fromUtf8("btnExp"))
        self.gridLayout_10.addWidget(self.btnExp, 3, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_10)
        self.gbNotes = QtGui.QGroupBox(self.centralwidget)
        self.gbNotes.setGeometry(QtCore.QRect(5, 490, 221, 71))
        self.gbNotes.setObjectName(_fromUtf8("gbNotes"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.gbNotes)
        self.verticalLayout_6.setContentsMargins(2, 0, 2, 4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.teNotes = QtGui.QPlainTextEdit(self.gbNotes)
        self.teNotes.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.teNotes.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.teNotes.setBackgroundVisible(False)
        self.teNotes.setObjectName(_fromUtf8("teNotes"))
        self.verticalLayout_6.addWidget(self.teNotes)
        self.lblBlock = QtGui.QLabel(self.centralwidget)
        self.lblBlock.setGeometry(QtCore.QRect(5, 2, 91, 26))
        self.lblBlock.setStyleSheet(_fromUtf8("background-color: rgba(255, 0, 4, 200);\n"
"font: 14pt \"MS Shell Dlg 2\";"))
        self.lblBlock.setFrameShape(QtGui.QFrame.Box)
        self.lblBlock.setFrameShadow(QtGui.QFrame.Plain)
        self.lblBlock.setLineWidth(1)
        self.lblBlock.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBlock.setObjectName(_fromUtf8("lblBlock"))
        win_st.setCentralWidget(self.centralwidget)

        self.retranslateUi(win_st)
        self.stackedWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(win_st)

    def retranslateUi(self, win_st):
        win_st.setWindowTitle(_translate("win_st", "Scan-A-Gator", None))
        self.lblBotStatus.setText(_translate("win_st", "UNSAVED", None))
        self.lblBotMsg.setText(_translate("win_st", "STATUS:", None))
        self.lblBotDim.setText(_translate("win_st", "250px (300ms) by 100px (23uM)", None))
        self.lblBotPockel.setText(_translate("win_st", "pockel: 5", None))
        self.lblBotPmt.setText(_translate("win_st", "PMT R=850 G=625", None))
        self.gbStructure.setTitle(_translate("win_st", "STRUCTURE", None))
        __sortingEnabled = self.listStruct.isSortingEnabled()
        self.listStruct.setSortingEnabled(False)
        item = self.listStruct.item(0)
        item.setText(_translate("win_st", "D1", None))
        item = self.listStruct.item(1)
        item.setText(_translate("win_st", "S1", None))
        item = self.listStruct.item(2)
        item.setText(_translate("win_st", "S2", None))
        item = self.listStruct.item(3)
        item.setText(_translate("win_st", "S3", None))
        item = self.listStruct.item(4)
        item.setText(_translate("win_st", "D2", None))
        self.listStruct.setSortingEnabled(__sortingEnabled)
        self.btnStIns.setText(_translate("win_st", "insert", None))
        self.btnStDel.setText(_translate("win_st", "delete", None))
        self.btnStAuto.setText(_translate("win_st", "auto 1", None))
        self.btnStrRename.setText(_translate("win_st", "rename", None))
        self.lineStructure.setText(_translate("win_st", "structure", None))
        self.lblStrB.setText(_translate("win_st", "B=55", None))
        self.lblStrA.setText(_translate("win_st", "A=54", None))
        self.lblStrW.setText(_translate("win_st", "W=1", None))
        self.gbLinescan.setTitle(_translate("win_st", "LineScan - Structure Editor", None))
        self.lblRef.setText(_translate("win_st", "REF", None))
        self.lblPK.setText(_translate("win_st", "peaks", None))
        self.lblLS.setText(_translate("win_st", "LS          ", None))
        self.lblOL.setText(_translate("win_st", "          OL", None))
        self.gbCalib.setTitle(_translate("win_st", "CALIBRATION", None))
        self.label_3.setText(_translate("win_st", "Rmax", None))
        self.label_4.setText(_translate("win_st", "Gmax", None))
        self.label_10.setText(_translate("win_st", "M", None))
        self.lblM.setText(_translate("win_st", "0.3423", None))
        self.gbTime.setTitle(_translate("win_st", "TIME DOMAIN (ms)", None))
        self.lineAV.setText(_translate("win_st", "123.4", None))
        self.linePK.setText(_translate("win_st", "122", None))
        self.label_11.setText(_translate("win_st", "Avg:", None))
        self.label_19.setText(_translate("win_st", "Msr:", None))
        self.lineBL.setText(_translate("win_st", "50,100", None))
        self.label_15.setText(_translate("win_st", "Ev:", None))
        self.label_14.setText(_translate("win_st", "BL:", None))
        self.lineMS.setText(_translate("win_st", "100,250", None))
        self.lineEV.setText(_translate("win_st", "100,120,140,160,180", None))
        self.label_12.setText(_translate("win_st", "Pk:", None))
        self.btnTimeUpdate.setText(_translate("win_st", "UPDATE", None))
        self.gbPreview.setTitle(_translate("win_st", "PREVIEW", None))
        self.cbPrv.setItemText(0, _translate("win_st", "(dG)/R", None))
        self.cbPrv.setItemText(1, _translate("win_st", "raw PMT", None))
        self.cbPrv.setItemText(2, _translate("win_st", "delta PMT", None))
        self.cbPrvMax.setText(_translate("win_st", "maximum", None))
        self.cbPrvMin.setText(_translate("win_st", "minimum", None))
        self.linePrvMax.setText(_translate("win_st", "321", None))
        self.linePrvMin.setText(_translate("win_st", "123", None))
        self.btnPrvSweeps.setText(_translate("win_st", "sweeps", None))
        self.btnPrvPNG.setText(_translate("win_st", "PNG", None))
        self.gbCycles.setTitle(_translate("win_st", "CYCLES", None))
        __sortingEnabled = self.listCycles.isSortingEnabled()
        self.listCycles.setSortingEnabled(False)
        item = self.listCycles.item(0)
        item.setText(_translate("win_st", "01", None))
        item = self.listCycles.item(1)
        item.setText(_translate("win_st", "02", None))
        item = self.listCycles.item(2)
        item.setText(_translate("win_st", "03", None))
        item = self.listCycles.item(3)
        item.setText(_translate("win_st", "04", None))
        item = self.listCycles.item(4)
        item.setText(_translate("win_st", "05", None))
        item = self.listCycles.item(5)
        item.setText(_translate("win_st", "06", None))
        item = self.listCycles.item(6)
        item.setText(_translate("win_st", "07", None))
        item = self.listCycles.item(7)
        item.setText(_translate("win_st", "08", None))
        item = self.listCycles.item(8)
        item.setText(_translate("win_st", "09", None))
        item = self.listCycles.item(9)
        item.setText(_translate("win_st", "10", None))
        item = self.listCycles.item(10)
        item.setText(_translate("win_st", "11", None))
        item = self.listCycles.item(11)
        item.setText(_translate("win_st", "12", None))
        item = self.listCycles.item(12)
        item.setText(_translate("win_st", "13", None))
        item = self.listCycles.item(13)
        item.setText(_translate("win_st", "14", None))
        item = self.listCycles.item(14)
        item.setText(_translate("win_st", "15", None))
        self.listCycles.setSortingEnabled(__sortingEnabled)
        self.btnCycle1.setText(_translate("win_st", "1", None))
        self.btnCycleAll.setText(_translate("win_st", "A", None))
        self.btnCycleNone.setText(_translate("win_st", "N", None))
        self.label_5.setText(_translate("win_st", "Gaussian (px):", None))
        self.label_6.setText(_translate("win_st", "space", None))
        self.label_7.setText(_translate("win_st", "time", None))
        self.lblGraph.setText(_translate("win_st", "LINESCAN INTENSITY", None))
        self.gbPreview_2.setTitle(_translate("win_st", "LINESCAN", None))
        self.cbLS.setItemText(0, _translate("win_st", "G", None))
        self.cbLS.setItemText(1, _translate("win_st", "R", None))
        self.cbLS.setItemText(2, _translate("win_st", "dG/R", None))
        self.cbStretch.setText(_translate("win_st", "stretch", None))
        self.gbReport.setTitle(_translate("win_st", "LineScan - Report Generator", None))
        self.btnHTMLgen.setText(_translate("win_st", "GENERATE", None))
        self.btnHTMLrefresh.setText(_translate("win_st", "REFRESH", None))
        self.btnHTMLlaunch.setText(_translate("win_st", "LAUNCH", None))
        self.groupBox.setTitle(_translate("win_st", "LineScan - Experiment Designer", None))
        self.btnExpLaunch.setText(_translate("win_st", "LAUNCH EXPERIMENT GRAPHS", None))
        __sortingEnabled = self.listExperiments.isSortingEnabled()
        self.listExperiments.setSortingEnabled(False)
        item = self.listExperiments.item(0)
        item.setText(_translate("win_st", "[FILES]", None))
        item = self.listExperiments.item(1)
        item.setText(_translate("win_st", "LineScan-01112014-1240-728", None))
        item = self.listExperiments.item(2)
        item.setText(_translate("win_st", "LineScan-01112014-1240-729", None))
        item = self.listExperiments.item(3)
        item.setText(_translate("win_st", "LineScan-01112014-1240-730", None))
        self.listExperiments.setSortingEnabled(__sortingEnabled)
        self.btnExpLoad.setText(_translate("win_st", "Load (.sag)", None))
        self.btnExpSave.setText(_translate("win_st", "Save (.sag)", None))
        self.btnExpPush.setText(_translate("win_st", "push to pad", None))
        self.btnExpPull.setText(_translate("win_st", "pull from pad", None))
        self.btnExpClear.setText(_translate("win_st", "clear all", None))
        self.btnExpDel.setText(_translate("win_st", "delete selected", None))
        self.groupBox_3.setTitle(_translate("win_st", "Scratch Pad", None))
        self.teExperimentCode.setPlainText(_translate("win_st", "---\n"
"path = \"X:\\Data\\2P01\\2014\\2014-01\\2014-01-11 SH rat HPC stability\\LineScan-01112014-1240-728\"\n"
"structure = \"active\"\n"
"color = \"blue\"\n"
"title = \"before\"\n"
"---\n"
"path = \"X:\\Data\\2P01\\2014\\2014-01\\2014-01-11 SH rat HPC stability\\LineScan-01112014-1240-728\"\n"
"structure = \"active\"\n"
"color = \"red\"\n"
"title = \"after\"", None))
        self.groupBox_2.setTitle(_translate("win_st", "Data Viewer", None))
        self.teConfig.setPlainText(_translate("win_st", "style=[\'something awesome\']", None))
        self.gbRegistration.setTitle(_translate("win_st", "Registration", None))
        self.label_9.setText(_translate("win_st", "PC identification:", None))
        self.lblRegPCID.setText(_translate("win_st", "7953-1425", None))
        self.lblRegName.setText(_translate("win_st", "Scott Harden", None))
        self.label_2.setText(_translate("win_st", "Registered to:", None))
        self.lblRegKey.setText(_translate("win_st", "F30B-2D31-D90A-42B1", None))
        self.label_13.setText(_translate("win_st", "Registration Key:", None))
        self.groupBox_5.setTitle(_translate("win_st", "Distribution", None))
        self.label_8.setText(_translate("win_st", "Version:", None))
        self.lblVersion2.setText(_translate("win_st", "1.23", None))
        self.pushButton.setText(_translate("win_st", "download", None))
        self.label_28.setText(_translate("win_st", "Update:", None))
        self.label_16.setText(_translate("win_st", "Updated:", None))
        self.lblDistDate.setText(_translate("win_st", "2013-01-12", None))
        self.groupBox_6.setTitle(_translate("win_st", "License", None))
        self.teLicense.setHtml(_translate("win_st", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah </span></p></body></html>", None))
        self.groupBox_4.setTitle(_translate("win_st", "Z-Series", None))
        self.btnZproj.setText(_translate("win_st", "PROJECT", None))
        self.groupBox_7.setTitle(_translate("win_st", "T-Series", None))
        self.btnTgen.setText(_translate("win_st", "PLAY", None))
        self.lblProgram.setText(_translate("win_st", "Scan-A-Gator", None))
        self.btnPageLS.setText(_translate("win_st", "LS Editor", None))
        self.btnPageLSreport.setText(_translate("win_st", "LS Report", None))
        self.btnPageExperiment.setText(_translate("win_st", "LS Experiment", None))
        self.btnPageXML.setText(_translate("win_st", "View XML", None))
        self.btnPageConfig.setText(_translate("win_st", "View Config", None))
        self.lblVersion.setText(_translate("win_st", "v3.1", None))
        __sortingEnabled = self.listBrowser.isSortingEnabled()
        self.listBrowser.setSortingEnabled(False)
        item = self.listBrowser.item(0)
        item.setText(_translate("win_st", "[FILES]", None))
        item = self.listBrowser.item(1)
        item.setText(_translate("win_st", "276 - 6:04:23 PM (03) 350ms 120px", None))
        item = self.listBrowser.item(2)
        item.setText(_translate("win_st", "277 - 6:11:11 PM (03) 350ms 120px", None))
        self.listBrowser.setSortingEnabled(__sortingEnabled)
        self.groupBox_9.setTitle(_translate("win_st", "FILE BROWSER", None))
        self.btnBrowserLaunch.setText(_translate("win_st", "launch", None))
        self.btnBrowserPath.setText(_translate("win_st", "set path", None))
        self.btnBrowserRefresh.setText(_translate("win_st", "refresh", None))
        self.cbBrL.setText(_translate("win_st", "Linescan", None))
        self.cbBrS.setText(_translate("win_st", "Single", None))
        self.cbBrZ.setText(_translate("win_st", "Z stack", None))
        self.cbBrT.setText(_translate("win_st", "T series", None))
        self.cbBrAll.setText(_translate("win_st", "ALL", None))
        self.cbBrA.setText(_translate("win_st", "ABF", None))
        self.cbAtLeast.setText(_translate("win_st", "at least:", None))
        self.cbBrH.setText(_translate("win_st", "hidden", None))
        self.btnBrowserStore.setText(_translate("win_st", "store", None))
        self.gbConfiguration.setTitle(_translate("win_st", "CONFIGURATION", None))
        self.btnConfigClear.setText(_translate("win_st", "clear", None))
        self.btnConfigRevert.setText(_translate("win_st", "revert", None))
        self.btnConfigCopy.setText(_translate("win_st", "copy", None))
        self.btnConfigPaste.setText(_translate("win_st", "paste", None))
        self.btnConfigSave.setText(_translate("win_st", "SAVE", None))
        self.btnConfigFlag.setText(_translate("win_st", "FLAG", None))
        self.btnConfigHide.setText(_translate("win_st", "HIDE", None))
        self.btnExp.setText(_translate("win_st", "EXP", None))
        self.gbNotes.setTitle(_translate("win_st", "EXPERIMENT NOTES", None))
        self.teNotes.setPlainText(_translate("win_st", "notes\n"
"notes\n"
"notes\n"
"notes", None))
        self.lblBlock.setText(_translate("win_st", "[SHIELD]", None))

from PyQt4 import QtWebKit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    win_st = QtGui.QMainWindow()
    ui = Ui_win_st()
    ui.setupUi(win_st)
    win_st.show()
    sys.exit(app.exec_())

